### ISSUE TITLE
`NAMESPACE=1 mix release lexical --overwrite` won't work at the first time.

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#107]
use `rm -rf _build deps .lexical && mix deps.get && NAMESPACE=1 mix release lexical` build the release.

Then open a project, write some incorrect code, the diagnostics won't show, and the completion also won't work, but if you use `rm -rf _build deps .lexical && mix deps.get && mix release lexical && NAMESPACE=1 mix release lexical --overwrite` to build the release, everything works well.

**Comment by scohen** [comment]
I can confirm this and help narrow it down.
You do not need to delete the deps directory. You only need to do 
```
mix do deps.clean --all
mix release lexical --overwrite && NAMESPACE=true mix release lexical --overwrite
``
removing the second `mix release` call doesn't work.

**Comment by scohen** [comment]
We now have `make release.namespaced` which works reliably
