### ISSUE TITLE
Go to definition can't jump to the correct position if the target is editing

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#113]

**Comment by scohen** [comment]
i don't understand what this means.

**Comment by scottming** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/12830256/237035306-64ba1a40-3cfb-4aa4-b22a-263aedc98a0b.png">

What I mean is that I opened both the module and the defined module at the same time. If I am editing the defined module(not saved yet), then when I jump, it is likely to go to the wrong position, like in the picture below.

My cursor was on `Dummy.|print` in the test file, but the peek definition jumped to `|>`, which is incorrect. Therefore, this is a bug of ElixirSense.

**Comment by scohen** [comment]
This is fixed with the new indexer.
