### ISSUE TITLE
[Completion] if a module has struct and submodule, we should complete both struct and module 

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#122]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/12830256/234432504-bffadf5b-68fa-443c-957b-d7eed258114a.png">

Currently, we only complete the struct, which is annoying.

**Comment by scohen** [comment]
I'd argue that in your example, you shouldn't complete the module and only complete the struct, since your intention is to use a struct (the line starts with `%`) See if #137 works to fix this.
