### ISSUE TITLE
Enhance completion on test file context

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#178]
<img width="573" alt="image" src="https://github.com/lexical-lsp/lexical/assets/12830256/7ebe3f89-d174-427f-ac41-7b454d5e6b15">

These three completions won't help, same as the completions of `descri|` and `asser|`, because no one writes code like this:

```elixir
  test(message, var \\ quote do
    _
  end, contents)
```

It should be 

<img width="572" alt="image" src="https://github.com/lexical-lsp/lexical/assets/12830256/c0bece41-2c12-4497-b0a7-ba4aa4207101">

This is provided by luasnip.

**Comment by scohen** [comment]
All that needs to happen here is to detect the `test` macro in `server/code_intelligence/completion/translations/macro.ex` and provide snippets.

**Comment by Sleepful** [comment]
I cannot repro this, my suggestions come without the `quote` part
<img width="609" alt="Screen Shot 2023-06-03 at 12 01 02" src="https://github.com/lexical-lsp/lexical/assets/7144046/c4f8e43e-c297-4ec2-9ebf-f4736bc0b3b7">

**Comment by scohen** [comment]
The quote thing was due to the way elixir sense reports argument names. That should be fixed now

**Comment by scottming** [comment]
@Sleepful Steve fixed the quote thing, but we still need to remove the parentheses

**Comment by scohen** [comment]
You don't need to remove anything, all you need to do is add another clause in the macro translation I linked to above.

**Comment by scohen** [comment]
To be more clear: The reason you're seeing this behavior is that the macro translation is taking this code path:
https://github.com/lexical-lsp/lexical/blob/6c4545ffcafaac37bed1012d12e63a8aaa8b434f/apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex#L448

All that needs to be done is to add another function head before that path that checks for test functions and that returns a snippet (maybe several --one for no arguments, one with a context map, etc). 

It's maybe a five-line change, excepting tests.

**Comment by Sleepful** [comment]
Thank you, it is very clear what I need to do 😁 
The code for adding a snippet is very clear! I also see why it would be nice for library authors to add plugins so they can add their own snippets
