### ISSUE TITLE
Lower the priority of some default functions in the module's sorting order

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#183]
<img width="519" alt="image" src="https://github.com/lexical-lsp/lexical/assets/12830256/d43fbcda-8034-4be8-b1a5-262023b46840">

```elixir
module_info/0
__info__(atom)
```

**Comment by scohen** [comment]
This is easy; for functions, provide a default boost `using builder.boost(...)` for all functions _except_ double underscore and `module_info`

This would be in `server/code_intelligence/completion/translations/callable.ex`
