### ISSUE TITLE
When completing with pipe connection, remove the first parameter.

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#185]
<img width="461" alt="image" src="https://github.com/lexical-lsp/lexical/assets/12830256/a95bbf0c-c378-496c-9b06-319e829d9f20">

it should be `Enum.map(fun)~`

Manually deleting the first parameter is really annoying, even in vim mode, I still need to press many keys.

**Comment by scohen** [comment]
This should happen, I think there might be a bug in pipe detection

**Comment by scohen** [comment]
See here https://github.com/lexical-lsp/lexical/blob/main/apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex#L56
