### ISSUE TITLE
Lexical can not start when erlang not compiled with wx

### ISSUE THREAD

**Issue by BlindingDark** [lexical-lsp/lexical#199]
Hi there, I get an error when I try to start lexical

```erlang
    ...
   {load_failed, "Failed to load NIF library: 'dlopen(/path/to/wx/priv/erl_gl.so' (no such file)'"}}}
    ...
```

So I recompiled Erlang OTP with wxwidgets and the error disappeared.
So wx dependency is necessary?
Thanks!

**Comment by scohen** [comment]
Hmm, I thought we solved this before, but looking at `mix.exs`, wx is still there. I'll remove it.
