### ISSUE TITLE
Not getting configuration from Application.compile_env

### ISSUE THREAD

**Issue by crbelaus** [lexical-lsp/lexical#214]
I'm not sure how to explain this problem but it looks to me as if Lexical is not being able to read the application's compile env and throws warnings as if the configuration wasn't set.

To reproduce it create an empty mix project: `mix new lexical_test`.

Then create a `config/config.exs` file with the following content:

```elixir
import Config

config :lexical_test, :date_helper, Date
```

And a `lib/lexical_test.ex` file with the following content:

```elixir
defmodule LexicalTest do
  @date_helper Application.compile_env(:lexical_test, :date_helper)

  def hello do
    @date_helper.utc_today()
  end
end
```

My expectation is that the `@date_helper` constant contains the `Date` module as we have set in the configuration. Lexical seems unable to understand this and throws the following warning:

```
[{
	"resource": "/Users/crbelaus/Developer/lexical_test/lib/lexical_test.ex",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "nil.utc_today/0 is undefined (module nil is not available or is yet to be defined)",
	"source": "Elixir",
	"startLineNumber": 5,
	"startColumn": 5,
	"endLineNumber": 6,
	"endColumn": 1
}]
```

I know that I could read the configuration in runtime using `Application.get_env` and that doesn't raise a warning. Anyway I'm curious about this warning as running `mix compile` handles this case just fine.

**Comment by scottming** [comment]
To be honest, I don't know why this issue occurred temporarily. I suspect that the config file was not loaded before `Mix.tasks.run("compile")`,  because `@date_helper Application.compile_env(:lexical_test, :date_helper, Date)` did not have this problem.

I will take a deep look at this issue when I have time.

**Comment by scohen** [comment]
@crbelaus Thanks for the detailed description and reproduction steps.

**Comment by crbelaus** [comment]
Thanks! Just compiled the project with the latest changes and the problem is gone 🙇
