### ISSUE TITLE
Support for `Find References`?

### ISSUE THREAD

**Issue by megalithic** [lexical-lsp/lexical#238]
I see it's on a roadmap (though no existing branches/PR towards it); in the meantime, what means are you using for `Find References` in your current editor of choice? Excellent work thus far to all the contribs!

**Comment by scohen** [comment]
Honestly, find_references has been so unreliable for me in elixir that I just use `ripgrep`. 
This will be the next thing on the docket once we get some of the current PRs merged and stabilized.

**Comment by scohen** [comment]
We're tracking this already, it's on the roadmap, and as such, I'm going to close this issue.
