### ISSUE TITLE
Support Elixir 1.15

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#243]
There are a _ton_ of failures under elixir 1.15, likely due to all the compiler work they did.

**Comment by scohen** [comment]
I've been going through the codebase and looking at the failing tests. I'm going to put my thoughts here as I find things.

The first tests I looked at are around code compilation; It appears that our `capture_io` methodology is breaking. Ironically, this is because all the diagnostics are now going through a logging mechanism which can now be captured via `Code.with_diagnostics`. The lesser irony is that this will make our code paths diverge between elixir > 1.15 and elixir < 1.15. 
We might be able to bring enough of the more modern compiler into our `Future` package so we can use it; I don't think the syntax has changed much since 1.13. 

If we can't do this, we'll have to have one code path that uses `capture_io` and another that uses `Code.with_diagnostics`. Kind of annoying, but at least the path forward is better.

**Comment by scottming** [comment]
https://github.com/elixir-lang/elixir/pull/12742

cc @scohen

**Comment by scottming** [comment]
> we'll have to have one code path that uses capture_io and another that uses Code.with_diagnostics

I think for diagnostics, this way might be more easier.
