### ISSUE TITLE
Function ordering needs work

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#263]
I think function ordering needs some help; it should be sorted with lower arity functions first, currently, higher arity functions come first.

**Comment by Nezteb** [comment]
A few qestions. I found some relevant tests:

- https://github.com/lexical-lsp/lexical/blob/185152d56f9a357bd98e704de3bd2c752f3db0ee/apps/server/test/lexical/server/code_intelligence/completion/translations/function_test.exs#L236
- https://github.com/lexical-lsp/lexical/blob/185152d56f9a357bd98e704de3bd2c752f3db0ee/apps/server/test/lexical/server/code_intelligence/completion_test.exs#L162
- https://github.com/lexical-lsp/lexical/blob/185152d56f9a357bd98e704de3bd2c752f3db0ee/apps/server/test/lexical/server/code_intelligence/completion/translations/macro_test.exs#L593

However, if I add `IO.inspect` to those tests to view the actual completions, the lower arity functions are already first in the list. Am I looking in the wrong place?

After a few glances at implementation code, my initial idea was to add a new `arity_boost` variable here: https://github.com/lexical-lsp/lexical/blob/1bd442e72fb82af89ddb9c63279d3dda084ff408/apps/server/lib/lexical/server/code_intelligence/completion/env.ex#L318, but I'm not sure if that's the correct place for a fix.

Thoughts?

**Comment by scohen** [comment]
@Nezteb I think I'd keep the local / global things, but maybe change the boost to have three characters rather than one. 
i.e.
```
000_000_#{item.label}
```
You'll also need to `String.pad_leading` the boosts now.
