### ISSUE TITLE
Lexical Vs ElixirLS Vs NextLS

### ISSUE THREAD

**Issue by cvkmohan** [lexical-lsp/lexical#271]
Suddenly, there is a flurry of influx of Language Servers in Elixir world! For the developers it is certainly a good news.
My question is - ElixirLS is oldest - and - looks feature complete. NextLS docs say - it wants to get feature parity with ElixirLS. Where does Lexical stand? I mean - would I be able to replace the Language Server setting of say NextLS - and - specify Lexical there? Or, Lexical is going to comeup with its own editor extension? In a way developers will have 3 different routes - and - each is incompatible with other?
Ofcourse, this is not an issue - but - discussions are not enabled for the project - so I am forced to put it here.  Sorry, if it sounds a novice question.

**Comment by scohen** [comment]
I think lexical is going to take a different tack than the others. I'm not really interested in having adding a bunch of features to check off boxes on a project's website. Rather, I think that each feature needs to be considered and crafted so it feels good in the developer's hands. To that end, Lexical is focusing on the developer experience first, and adding features second.  That said, we do intend to add well crafted features that you'll like. I'm especially proud of our formatting and completion features. Formatting is lightning fast and respects your project's configuration, even if you change it while editing. The completion is also context aware, which means it understands if you're inside a function capture (where it will suggest `foo/3` as an option), a pipeline (were it will omit the first argument for you) or inside an alias and you hit `.` (where it won't suggest the module's functions, only submodules). 

On editor extensions:
It depends on your editor. Lexical currently has a bespoke vscode extension. For other editors, lexical works with the elixir-ls extensions, you can just replace the path to elixir-ls with the path to `start_lexical.sh` and you should be good.

I think it's a good idea for lexical to have extensions for common editors though. In the future, lexical should have some amount of configurability that really can only be accomplished via an editor extension. Plus, editors should allow one to select the language server they wish to run, and this can only be accomplished via multiple editor extensions.

The alternative would be to have one editor extension for all three elixir language servers, but they all support different features and different configuration. I don't think that would be sustainable; what does it mean to enable dialyzer support for a language server that doesn't support dialyzer? That's not great UX and will lead to a lot of confusion.

Don't feel bad about posting here, I'll enable discussions.

**Comment by cvkmohan** [comment]
Thanks for the prompt and detailed response. So, if I would want to try this out - 
1. Downgrade to Erlang 25. 
2. Install vscode extension.
and I am ready to go with code suggestions and format on save etc?

**Comment by scohen** [comment]
Yes, though we haven't done a release of lexical in a while. I want to do one when I land the PR for supporting multiple versions, because then things should just work for you, though not if you're using erlang 26.

If you want the latest and greatest, I suggest pulling the latest source and compiling it under 25. There's a configuration option in the vscdoe extension where you can point it to lexical's compilation directory.

**Comment by cvkmohan** [comment]
I can confirm that with the above steps, it is working beautifully for `vscode`. 
Looking forward to your release soon.... and support for erlang 26 after that.

**Comment by scohen** [comment]
@cvkmohan the new release is out. 0.2.2

**Comment by cvkmohan** [comment]
Thanks and Yes. Observed it. In fact, now it is a plain installation from vscode. No other config is necessary.
I hope you make it available for Erlang 26 also soon.
In the brief usage of these 2 days - I can say that - autocompletion is far superior - and formatting is smooth as cheese. :)
Keep going. All the best.
