### ISSUE TITLE
Lexical doesn't start or print errors when a dependency requires compile-time configuration

### ISSUE THREAD

**Issue by michallepicki** [lexical-lsp/lexical#273]
MacOS Ventura 13.4.1 (Apple Sillicon)
Erlang 25.2.3
Elixir 1.14.5-otp-25
VSCode 1.77.0
Lexical LSP extension v0.0.3
Lexical [0af6418](https://github.com/lexical-lsp/lexical/commit/0af64186227e0d993d2abdc54eb9407ea206dd69) (configured with `lexical.server.releasePathOverride`)

Project that reproduces the issue: https://github.com/michallepicki/lexical_test
(the project uses a path dependency, but the same happens with git dependencies as well)

The project compiles when running `mix compile`, because the required config is set in project's `config/config.exs` file.

Lexical gets stuck and doesn't work for this project, and when inspecting the Lexical output in VSCode, I see:
```
could not compile dependency :path_dep, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile path_dep", update it with "mix deps.update path_dep" or clean it with "mix deps.clean path_dep"
```
but no errors have been printed there (only warnings).

I think this is because this dependency doesn't follow good practices, and requires some compile-time config to be set to compile at all. I'm not sure if Lexical should load project's config to make this work, or should this limitation be documented

**Comment by scohen** [comment]
Interesting, thank you for the detailed investigation and reproduction steps! I'll get right on this.
