### ISSUE TITLE
Weird compilation error when saving a .html.heex file

### ISSUE THREAD

**Issue by crbelaus** [lexical-lsp/lexical#277]
Not sure if this should be reported in this repo or in the VSCode extension.

I've noticed a strange error when saving .html.heex files. When I save any .html.heex file the autoformatter works just fine but then I get a syntax error in the first `<` character of the first HTML tag.

> Syntax error before: `<`

<img width="688" alt="image" src="https://github.com/lexical-lsp/lexical/assets/2965623/e8963b71-22d0-4d1d-8317-f2f415d89153">

<img width="310" alt="image" src="https://github.com/lexical-lsp/lexical/assets/2965623/6cdcf29c-5b73-4148-87f3-b203b6164854">

The syntax is valid and everything compiles just fine with `mix compile` and with elixir-ls.

**Comment by scohen** [comment]
Interesting, we've done nothing to support `heex`. I'll have to take a look.

**Comment by scohen** [comment]
Tracking this in #100 
Thank you for the report, I think we understand what's happening

**Comment by crbelaus** [comment]
Thanks! 🙇
