### ISSUE TITLE
Nix build config

### ISSUE THREAD

**Issue by Nezteb** [lexical-lsp/lexical#288]
Nix is a large topic, but `elixir-ls` has a Nix package: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/beam-modules/elixir-ls/default.nix

This is related to https://github.com/lexical-lsp/lexical/issues/255, but Nix is relatively niche so I figured I'd make it a new issue.

**Comment by scohen** [comment]
@Nezteb Check out https://github.com/lexical-lsp/lexical/tree/main/nix
Just merged.

**Comment by Nezteb** [comment]
Oh dang, nice! https://github.com/lexical-lsp/lexical/pull/175

I should have known it'd be @hauleth 😏

gg!
