### ISSUE TITLE
Lexical crashes on vscode start

### ISSUE THREAD

**Issue by alexloukissas** [lexical-lsp/lexical#300]
Trying out lexical for the first time, seems to crash as soon as I open vscode. Logs below:

```
Starting lexical release in "/Users/aloukissas/Library/Application Support/Code/User/globalStorage/lexical-lsp.lexical/lexical_install/lexical"
init terminating in do_boot ({load_failed,[proc_lib,gen_server,lists,logger_simple_h,logger_config,supervisor,logger_server,gen,gen_event,file_io_server,file_server,filename,file,logger_filters,kernel,heart,ets,erl_parse,application_master,code_server,error_handler,application_controller,application,erl_lint,error_logger,erl_eval,code,logger_backend,logger]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:32:13 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:32:13 PM] Connection to server got closed. Server will restart.
true
[Error - 2:32:13 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[erl_eval,supervisor,lists,proc_lib,logger_config,logger_simple_h,logger_filters,file_server,filename,ets,file,application,erl_parse,code,kernel,file_io_server,gen,heart,gen_server,gen_event,erl_lint,error_logger,code_server,application_master,application_controller,error_handler,logger_backend,logger_server,logger]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:32:14 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:32:14 PM] Connection to server got closed. Server will restart.
true
[Error - 2:32:14 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[proc_lib,heart,supervisor,gen,logger_backend,logger_server,logger_config,logger,kernel,gen_server,file_server,gen_event,filename,file_io_server,error_logger,ets,file,code,erl_parse,erl_lint,erl_eval,code_server,application_controller,application,application_master,logger_simple_h,error_handler,lists,logger_filters]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:32:15 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:32:15 PM] Connection to server got closed. Server will restart.
true
[Error - 2:32:15 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:32:15 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[kernel,supervisor,logger_config,logger_server,proc_lib,logger,heart,code_server,file,logger_backend,erl_parse,filename,error_logger,ets,erl_lint,erl_eval,application_controller,error_handler,application,gen_event,gen_server,file_server,file_io_server,gen,code,application_master,lists,logger_simple_h,logger_filters]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:32:15 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:32:15 PM] Connection to server got closed. Server will restart.
true
[Error - 2:32:15 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:32:15 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[logger_simple_h,lists,supervisor,logger_config,gen,logger,logger_filters,heart,gen_event,filename,file_io_server,file_server,ets,file,application_controller,error_handler,application,logger_server,error_logger,gen_server,erl_parse,erl_lint,erl_eval,code_server,application_master,code,proc_lib,logger_backend,kernel]})

Crash dump is being written to: erl_crash.dump...done
[Error - 2:32:16 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:32:16 PM] The Lexical server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:32:16 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:32:16 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Any hints?

**Comment by Tuxified** [comment]
Sounds like a mismatch between your Erlang/OTP version and the one in which Lexical is running. Can you provide more details? Which Elixir, Erlang/OTP are you running, how did you install it, what's your OS... etc

**Comment by alexloukissas** [comment]
We use asdf in our repo, this is the versions file:

```
erlang 25.1.2
elixir 1.14.2-otp-25
nodejs 16.14.0
```

I'm on MacOS 13.3 (arm64)

**Comment by scottming** [comment]
@alexloukissas Did you check this:

https://github.com/lexical-lsp/vscode-lexical#known-issues

> If you cannot use one of the above versions of Erlang, a workaround is to clone the [Lexical language server repo](https://github.com/lexical-lsp/lexical), change include_erts to true in mix.exs, build a release following the instructions in the README and [configure the extension to use that local release](https://github.com/lexical-lsp/vscode-lexical#lexicalserverreleasepathoverride)

**Comment by simonmcconnell** [comment]
@scottming but they are supported verions, no?  Is it the fact that they're installed with `asdf` that is the issue?

**Comment by Tuxified** [comment]
Yes, those are supported versions under which Lexical should work correctly. However, the release is built with one specific version of Elixir etc which doesn't seem to play nice with the version the @alexloukissas has installed. Until we figure out how to build specific versions matching the installed versions of Elixir (or build upon installation), the best way is to download the source code and build a release yourself.

@alexloukissas does that help? are the guides clear enough on how to build a release yourself?

**Comment by scottming** [comment]
@simonmcconnell @Tuxified 

This is still an old issue; our updated documentation has made it even more unclear: https://github.com/lexical-lsp/vscode-lexical/pull/32/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

The listed versions are all supported versions, but there is a prerequisite that the lexical version must be built with the same `erl` version as the one you are running your project with.

Suppose you want to run lexical with a different `erl` version. In that case, you must modify the lexical source code by changing `include_erts: false` to `include_erts: true`, and follow the instructions in the Vscose-Lexical documentation to modify the runtime path.

**Comment by scottming** [comment]
Related issues:

* https://github.com/lexical-lsp/vscode-lexical/issues/24
* https://github.com/lexical-lsp/lexical/issues/255
* https://github.com/lexical-lsp/lexical/issues/280

**Comment by simonmcconnell** [comment]
Yeah, the readme is misleading.  

I feel like elixir-ls might have recently changed to building based on whatever version you're running.  It certainly does something with asdf on startup 🤷

**Comment by scohen** [comment]
I don't think you need to match exact versions if `include_erts` is false; You should be able to use an _older_ version than your project runs in.

**Comment by scohen** [comment]
I'm closing this as a duplicate, understand that fixing this is my highest priority right now.
