### ISSUE TITLE
Request: please consider adding to OpenVSX marketplace

### ISSUE THREAD

**Issue by apxcarter** [lexical-lsp/lexical#302]
For those using open source versions of VS Code, or platforms like Gitpod, we don't have access to the MS VS Code marketplace, and they have pretty strict rules around using vsx files from their marketplace elsewhere. 

If you submit to OpenVSX, then it becomes available as an easily installable extension for people using the open source versions of VS Code.

There are instructions here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thanks for your time!

**Comment by scohen** [comment]
@apxcarter we'll definitely consider it; I would like it to work reliably before we add another marketplace.

**Comment by elevesque-nexapp** [comment]
@apxcarter would you mind moving the issue over to https://github.com/lexical-lsp/vscode-lexical? That's where support for OpenVSX would have to be added. Thanks!

**Comment by Blond11516** [comment]
@apxcarter Would you mind moving this over to https://github.com/lexical-lsp/vscode-lexical please? That's where support for OpenVSX would have to be added. Thanks!
