### ISSUE TITLE
Lexical doesn't work with neovim 0.8.2

### ISSUE THREAD

**Issue by zeionara** [lexical-lsp/lexical#306]
Tried to run the tool using neovim according to [the instructions](https://github.com/lexical-lsp/lexical/blob/main/pages/installation.md#neovim) - nothing happens. The process starts when I open an elixir file in the editor, but no error logged, no warnings, just nothing happens. Is it possible to enable logging somehow?

My versions of the tools:

```
elixir 1.15.3-otp-25
erlang 25.3.2.2
neovim 0.8.2
```

**Comment by scohen** [comment]
It definitely works with neovim, @scottming uses it. There should be logs in the `.lexical` directory in your project, I suspect it's because of releases not working reliably across elixir / erlang versions.

**Comment by zeionara** [comment]
Yeah, thanks, now I see, there is a log file indeed. But I can't deduce anything from it. @scottming, which versions of elixir / erlang do you use?

**Comment by scohen** [comment]
@zeionara if you share the log file, we can definitely help ;)

if you've set `include_erts: true` the only rule is you need to build lexical with the [lowest version of elixir and erlang that any of your projects use](https://github.com/lexical-lsp/lexical/blob/main/pages/installation.md#caveats).

**Comment by scottming** [comment]
@zeionara Did you try this minimal config: https://github.com/scottming/nvim-mini-for-lexical

**Comment by zeionara** [comment]
> @zeionara Did you try this minimal config: https://github.com/scottming/nvim-mini-for-lexical

Yes, this config looks just like the example in the readme, and my config is essentially the same (although I dont use `lazy.nvim`). My config has the following content:

```lua
local lspconfig = require("lspconfig")
local configs = require("lspconfig.configs")

local lexical_config = {
    filetypes = { "elixir", "eelixir" },
    cmd = { "/usr/local/lexical/_build/dev/rel/lexical/start_lexical.sh" },
    settings = {}
}

local attach = function(client)
    print('Lexical has started')
end

if not configs.lexical then
    configs.lexical = {
        default_config = {
            filetypes = lexical_config.filetypes,
            cmd = lexical_config.cmd,
            root_dir = function(fname)
                return lspconfig.util.root_pattern("mix.exs", ".git")(fname) or vim.loop.os_homedir()
            end,
            settings = lexical_config.settings
        }
    }
end

lspconfig.lexical.setup({
    on_attach = attach
})
```

**Comment by scottming** [comment]
Looking at your logs I see that you are not using `NAMESPACE=1`. And have you tried opening a brand new project? Use `mix new dummy` to create a brand new project and then open an `ex` file.

Try `NAMESPACE=1 mix release lexical --overwrite` to do the release, and again try this minimal config: https://github.com/scottming/nvim-mini-for-lexical

**Comment by scottming** [comment]
And I think you should upgrade Neovim from `0.8.2` to `NVIM v0.9.1` first, they changed something related LSP client.

@zeionara

**Comment by scottming** [comment]
> But I can't deduce anything from it. @scottming, which versions of elixir / erlang do you use?

I mainly use `1.15.4-otp-25` and `25.3.2.4`, everything works very well with `nvim 0.9.1`

**Comment by zeionara** [comment]
> Looking at your logs I see that you are not using `NAMESPACE=1`. And have you tried opening a brand new project?
> 
> Try `NAMESPACE=1 mix release lexical --overwrite` to do the release, and again try this minimal config: https://github.com/scottming/nvim-mini-for-lexical
> 
> Then use `mix new dummy` to create a brand new project and then open an `ex` file.

Ok, what I've just done:

1. Recompiled the server with `NAMESPACE=1`;
1. Created a dummy project as you said;
1. Cloned minimall config: `git clone git@github.com:scottming/nvim-mini-for-lexical.git ~/.config/nvim-mini-for-lexical`;
1. Opened an elixir file:

```sh
cd dummy
NVIM_APPNAME=nvim-mini-for-lexical nvim lib/dummy.ex
```

Now server is not even starting. Will try upgrade neovim and see if it helps

**Comment by scottming** [comment]
@zeionara I don't know what is `snap`, I mainly use `homebrew` to install and upgrade NeoVim

**Comment by scohen** [comment]
Snap is a way to install applications across linux distributions.
