### ISSUE TITLE
bug: `could not load module :future_elixir_interpolation`

### ISSUE THREAD

**Issue by chukinas** [lexical-lsp/lexical#324]
I tried creating a minimal neovim setup using https://github.com/scottming/nvim-mini-for-lexical/, but when I open an elixir file, I get the error `Client 1 quit with exit code 1 and signal 0`.

Is there any way to debug or see logs so I can see more detail around what's going on? I'm not even sure at this point if that error is return by the language server or something in neovim.

**Comment by chukinas** [comment]
Oh cool, so I found the `:LspLog` command and found this error in the neovim LSP logs:
```
[START][2023-08-13 08:46:07] LSP logging initiated
[ERROR][2023-08-13 08:46:07] .../vim/lsp/rpc.lua:734    "rpc"   "/home/jc/projects/opensource/lexical/_build/dev/package/lexical/bin/start_lexical.sh"  "stderr"        '** (Argume
ntError) could not load module :future_elixir_interpolation due to reason :badfile\n    (elixir 1.15.4) lib/code.ex:1779: Code.ensure_loaded!/1\n    (elixir 1.15.4) lib/enum.ex:98
4: Enum."-each/2-lists^foreach/1-0-"/2\n    lib/lexical/server/boot.ex:17: LXical.Server.Boot.start/0\n    nofile:1: (file)\n    (stdlib 4.0) erl_eval.erl:748: :erl_eval.do_apply/
7\n'
```

I saw something about this when I was following the Lexical setup steps. I'll go back to those steps and see what I can learn.

**Comment by zachallaun** [comment]
I ran into the same thing yesterday, specifically when switching the OTP version that I was packaging lexical with. In my case, it was fixed by deleting my `_build` directory (in lexical) and recompiling/packaging. Hope the same works for you to get things up and running!

Would of course be good to figure out what's going on here -- maybe `mix package` needs to be forcing compilation to ensure that old build artifacts aren't being used?

**Comment by scohen** [comment]
@chukinas, Did you build on a newer version of erlang than your project uses?

**Comment by scohen** [comment]
@chukinas Did you get a chance to try the branch in #332?

**Comment by scohen** [comment]
any updates, @chukinas ?

**Comment by scohen** [comment]
@chukinas I'm closing due to non-response, and am assuming it works for you now.
