### ISSUE TITLE
Nix flake issue

### ISSUE THREAD

**Issue by Leastrio** [lexical-lsp/lexical#326]
The nix flake is outdated with the new package command and deps hash. I took at attempt at updating the hash and packaging command. 
Updating the deps hash gives me this error
```
Unchecked dependencies for environment prod:
       * elixir_sense (https://github.com/elixir-lsp/elixir_sense.git)
         lock mismatch: the dependency is out of date. To fetch locked version run "mix deps.get"
       ** (Mix) Can't continue due to errors on dependencies
```
So in return i tried another attempt by deleting the mix.lock file which gave me this error
```
== Compilation error in file lib/path_glob/parser.ex ==
** (CompileError) lib/path_glob/parser.ex:2: module NimbleParsec is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module

could not compile dependency :path_glob, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile path_glob", update it with "mix deps.update path_glob" or clean it with "mix deps.clean path_glob"
```

Any ideas on what I could do to fix these errors?

**Comment by scohen** [comment]
@hauleth , any ideas?

**Comment by hauleth** [comment]
I wilk look into it in a moment.

**Comment by scohen** [comment]
@hauleth I would like to release 0.3 this week, and would really appreciate it if the nix flakes work when I do. If you can't look at it in the next couple of days, I think I'm going to need to remove them so I can do a release.

**Comment by scohen** [comment]
@Leastrio, @hauleth has updated the flake in #344. Can you please take a look?

**Comment by Leastrio** [comment]
sorry for the late reply, it works .
