### ISSUE TITLE
Print lexical version when it's starting

### ISSUE THREAD

**Issue by stefanluptak** [lexical-lsp/lexical#352]
I would like to see in my VSCode logs for the Lexical LSP extension what's the version of the Lexical that I am using, so I know if I should update it or not. :-) Thank you.

**Comment by scohen** [comment]
@Blond11516 doesn't the vscode extension check for a new version on startup?

**Comment by Blond11516** [comment]
@stefanluptak Are you using a custom build or the extension's auto-install?

If using auto-install, it will always try to download the latest release from github yes.

The extension has no idea what version you have if using a custom build however.

**Comment by scohen** [comment]
nor could it, a custom build, by definition doesn't have a version (it thinks it's whatever the last released version was).

**Comment by stefanluptak** [comment]
Sorry, I was a bit confused when I was experimenting with Elixir LSPs. You're right @scohen. I am closing this issue as it's irrelevant.
