### ISSUE TITLE
Increase or remove timeout for indexing

### ISSUE THREAD

**Issue by zachallaun** [lexical-lsp/lexical#369]
My relatively old computer takes longer than 20 seconds to index Lexical, so it ends up timing out and looping indefinitely. Since it's basically chugging along during indexing, that ends up slowing everything down pretty considerably, so regular compilation also ends up taking much longer than usual. 

@scohen we should prob remove (or dramatically increase) the timeout for indexing, or make it a function of the number of chunks.

**Comment by philipgiuliani** [comment]
I am probably having the same problem in a large project! After waiting for 1h and having my pc use 6 cores with 100% usage i disabled the lsp for now 😅

**Comment by skbolton** [comment]
This is complete by #371 right?

**Comment by zachallaun** [comment]
Yes, thank you for the reminder!
