### ISSUE TITLE
Add support for `textDocument/documentSymbol`

### ISSUE THREAD

**Issue by skbolton** [lexical-lsp/lexical#382]
Been enjoying my time so far with lexical! This is one of the features that I am direly missing.

I use this all the time in a file to jump to a function or symbol by name. This is one that I might possibly take a stab at being my first contribution.

**Comment by scohen** [comment]
We welcome the contribution, but I think you should hold off.

We're building a search and indexing solution, and i'm designing it with an eye to making document / workspace symbols very easy to implement. We're indexing things and keeping track of what they are and what their context is (namely which parents and children they have). Once this is complete, a document's symbols should be a matter of fetching all the items in a document and reconstructing the hierarchy. 

I'd hate to see you do a lot of work without this backing.

**Comment by scohen** [comment]
If you're champing at the bit to work on something, why not try: #96 ? Hop on our discord and we'll guide you through it.

**Comment by skbolton** [comment]
I'll take a look thanks for the heads up
