### ISSUE TITLE
Memory leak when indexer is enabled

### ISSUE THREAD

**Issue by DReigada** [lexical-lsp/lexical#404]
It seems that there's some kind of memory leak when the new indexer is enabled.
The issue seems to stop happening after the commit where the indexer was disabled: a170acb2d35eaecb705e6411c8068e445741e28f

How to reproduce:
1. use any version between the indexer being enabled and disabled (eg 85c90fb4a8d5e0e79efa0a26e2970f02dac5c6e7)
2. open a big project with VSCode 
3. let lexical hang in the background for some time
4. the beam.vm process should start using a large amount of memory (> 20GB)

**Comment by scohen** [comment]
I launched observer in the lexical project, and a standout was the Search store. Inside that, it looked like the fuzzy matcher had a lot of refc binary references, coming from subjects. It's likely that these weren't being freed.

**Comment by scohen** [comment]
@DReigada, can you give this branch a shot? https://github.com/lexical-lsp/lexical/tree/fuzzy-improvements

**Comment by zachallaun** [comment]
@scohen Just to confirm: #421 didn't address this, right? It was focused on initial memory consumption during a fresh indexing pass?

**Comment by scohen** [comment]
@zachallaun, no this issue should have been fixed by #421

**Comment by scohen** [comment]
@DReigada im going to close this issue, please repopen if #421 didjt address your issue (though a co-worker indicated that it was fixed on discord)
