### ISSUE TITLE
Skip build directory in indexing

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#456]
Presently, we index both the deps and _build directory, so source files in both directories will show up with when you call find references. This raises two questions:
 
  1. Should we index the `_build` directory?
  2. Should we index the `deps` directory

I think the answer to the first question is definitely no.
I'm not so sure about if we should skip the deps directory. I've found it sometimes useful to see usages of a particular module in dependencies, but I can also understand that results from dependencies clutter the results. 

This is a relatively easy fix; we just need to remove the build (and maybe the deps) directories from the [list of indexable files generated](https://github.com/lexical-lsp/lexical/blob/a6dd1011daa19c310b767d89d74126ac2e18881c/apps/remote_control/lib/lexical/remote_control/search/indexer.ex#L126).

**Comment by milinddethe15** [comment]
Hi, I want to work on this issue. Assign it to me.

**Comment by zachallaun** [comment]
@milinddethe15 We don't generally use the assignment feature except for cases where the assignee has specific domain knowledge that makes it appropriate for them to handle it, e.g. a bug report for a feature I introduced may be assigned to me.

Commenting here expressing interest is sufficient! If you have any further questions, don't hesitate to reach out or to ask questions [on Discord](https://discord.gg/BPJFN74uYX)!

**Comment by scohen** [comment]
( I assigned it to them anyways )

**Comment by Terbium-135** [comment]
What about making `deps` folder indexing a (user) option in the editor settings?

**Comment by scohen** [comment]
That's a larger change. Presently, Lexical doesn't have options, so we'd need to add the ability to have them.

My thoughts about deps are this. Usually, you're finding references to something you wrote, and in that instance, you're not going to get results from `_deps`. 

On the other hand, it might be useful if you want to search for one of your dependency's modules to see where it appears in another dependency or to get an idea of how pervasive it is. In that case, searching deps is useful (I've done this a bunch with Jason).
