### ISSUE TITLE
Undefined variable in heex template

### ISSUE THREAD

**Issue by crbelaus** [lexical-lsp/lexical#460]
Lexical is emitting an error saying that the `requested_ranges_form` variable is undefined, even though it is defined a little bit earlier in a `:let` attribute.

This is my day job code so I cannot post the entire code snippet but here is a screenshot:

![image](https://github.com/lexical-lsp/lexical/assets/2965623/240a0b23-d4ed-4027-9f25-a3ca44a85daa)

The error reported by Lexical is `undefined variable "requested_ranges_form"`. When running `mix compile --force` it does not report any warning on error as expected.

**Comment by scohen** [comment]
@scottming can you take a look when you have a chance?

**Comment by scottming** [comment]
@scohen sure, I will.
