### ISSUE TITLE
Unhelpful :: operator completion

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#474]
The operator `::` has a very unhelpful completion, completing to `::(left, right)`. It should be suppressed.

This is easy, it's a macro, and should be skipped by [adding a pattern match](https://github.com/lexical-lsp/lexical/blob/main/apps/server/lib/lexical/server/code_intelligence/completion/translations/macro.ex#L550).

**Comment by mdshamoon** [comment]
Hi @scohen can I pick up this issue. The project has been really helpful for me. Wanted to contribute back.

**Comment by scohen** [comment]
Fixed via #485
