### ISSUE TITLE
Server crashes on some projects for lsp-mode

### ISSUE THREAD

**Issue by wkirschbaum** [lexical-lsp/lexical#477]
I am getting this when opening a new project using lsp-mode. Both erlang and elixir gets compiled locally on linux and I am not using asdf or any other versioning tools. 

```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

```log
LSP :: Error from the Language Server: ** (ErlangError) Erlang error: {:erpc, :noconnection}
    (kernel 9.1) erpc.erl:710: :erpc.call/5
    (lx_server 0.3.0) lib/lexical/server/provider/handlers/code_action.ex:16: LXical.Server.Provider.Handlers.CodeAction.handle/2
    (lx_server 0.3.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
 (Internal Error)
Quit
LSP :: Error from the Language Server: ** (ErlangError) Erlang error: {:erpc, :noconnection}
    (kernel 9.1) erpc.erl:710: :erpc.call/5
    (lx_server 0.3.0) lib/lexical/server/provider/handlers/code_action.ex:16: LXical.Server.Provider.Handlers.CodeAction.handle/2
    (lx_server 0.3.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
 (Internal Error)
 ```
 
 Is there anything I can do to debug this further?

**Comment by wkirschbaum** [comment]
It only happens on some larger projects it seems, but have not tested it fully.

**Comment by wkirschbaum** [comment]
It might be on projects with a much older version of the .lexical directory, because when I delete it it seems to work afterwards.

**Comment by scohen** [comment]
> Is there anything I can do to debug this further?

Is that all from the logs in the `.lexical` directory? I feel like there should have been an error before that error. I'm going to assume that `epmd` is running for you.

**Comment by wkirschbaum** [comment]
I can't reproduce after I saw it once and deleted the directory. Sorry. Will log a new one if I see it again with sufficient detail

**Comment by scohen** [comment]
I think you ran into this:
https://github.com/lexical-lsp/lexical/pull/481
