### ISSUE TITLE
Emacs 30 + Eglot + Lexical

### ISSUE THREAD

**Issue by nicemaker** [lexical-lsp/lexical#483]
I followed your installation instructions but have some timeout issues

I think I have the latest Emacs version:
`GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2023-10-30`

On Ubuntu: `Ubuntu 22.04.3 LTS`

I packaged the project with 
`INDEXING_ENABLED=true mix package`

In my emacs config file, I just have this elixir specific code:

```
(use-package elixir-ts-mode
  :ensure t)
```

And this snippet from your instructions:
```
(with-eval-after-load 'eglot
  (setf (alist-get '(elixir-mode elixir-ts-mode heex-ts-mode)
                   eglot-server-programs
                   nil nil #'equal)
        (if (and (fboundp 'w32-shell-dos-semantics)
                 (w32-shell-dos-semantics))
            '("language_server.bat")
          (eglot-alternatives
           '("language_server.sh" "start_lexical.sh")))))
 ```
 
 Small sitenote: 
 The instructions just say
 `'("language_server.sh" "start_lexical.sh")`
Would be good to rewrite this a little so that its clear that it should be 
 `'("language_server.sh" "/my/home/projects/_build/dev/package/lexical/bin/start_lexical.sh")`
 
 
That worked! Yay!
```
[eglot] Connected! Server `Lexical' now managing `(elixir-ts-mode elixir-mode heex-ts-mode)' buffers in project `shopex'.
```

But each time I try find-references I got a timeout:
`jsonrpc-request: jsonrpc-error: "request id=49 failed:", (jsonrpc-error-message . "Timed out")`

Any ideas?

**Comment by nicemaker** [comment]
Another hint: Its not `find-refeences` specific. I also got a timeout for `eglot-format`

**Comment by scottming** [comment]
Did you try debug it with the debug_shell command?

**Comment by nicemaker** [comment]
In emacs I don't find that command...
where do I do that?

**Comment by nicemaker** [comment]
Not sure if I do that right, I did this in terminal

```
./debug_shell.sh lexical

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Could not contact remote node @127.0.0.1, reason: :nodedown. Aborting...
```

If this is correct that for some reasons lexical didn't start or shut down

**Comment by nicemaker** [comment]
I did this:

```
./debug_shell.sh shopex
```

shopex is the name of my project displayed in the successful connection mesgae

Iex opened:
```
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(manager-shopex-986@127.0.0.1)1> 
```

Then I tried to run `eglot-format` again.

In emacs I didn't get the timeout anymore but I got this message then:

```
helm-M-x-execute-command: jsonrpc-error: "request id=3 failed:", (jsonrpc-error-code . -32603), (jsonrpc-error-message . "** (ErlangError) Erlang error: {:erpc, :noconnection}
    (kernel 8.5.1) erpc.erl:710: :erpc.call/5
    (lx_server 0.3.0) lib/lexical/server/provider/handlers/formatting.ex:13: LXical.Server.Provider.Handlers.Formatting.handle/2
    (lx_server 0.3.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.14.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
"), (jsonrpc-error-data)
Mark set [2 times]
next-line: End of buffer [6 times]
next-line: End of buffer
```

Not sure if that's the place to look for the error or if I have to do something else in the iex terminal that opened

**Comment by nicemaker** [comment]
So I reinstalled erlang (26) and elixir (1.15.7) and  to open observer with  :observer.start.
No idea what I should look for.

Still got the same error in emacs, just with different elixir version.
```
helm-M-x-execute-command: jsonrpc-error: "request id=5 failed:", (jsonrpc-error-code . -32603), (jsonrpc-error-message . "** (ErlangError) Erlang error: {:erpc, :noconnection}
    (kernel 9.1) erpc.erl:710: :erpc.call/5
    (lx_server 0.3.0) lib/lexical/server/provider/handlers/formatting.ex:13: LXical.Server.Provider.Handlers.Formatting.handle/2
    (lx_server 0.3.0) lib/lexical/server/provider/queue.ex:99: anonymous fn/2 in LXical.Server.Provider.Queue.State.as_task/2
    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.7) lib/task/supervised.ex:36: Task.Supervised.reply/4
"), (jsonrpc-error-data)
Mark set [2 times]
```

**Comment by scohen** [comment]
@nicemaker I was away from lexical over the weekend. Let's try to figure out what's going on. 
First off, which OS are you using, and which specific versions of elixir and erlang (include all the version numbers, not just the major for erlang). It's worth noting that lexical doesn't work with erlang 26.0.0 and 26.0.1.

Lexical also writes log files to your project's root directory in the `.lexical` directory. These are more helpful to us than emacs's logs.

It looks to me like your project node isn't starting correctly, which is why the `:erpc` call is failing. I suspect your path isn't set up correctly, and the shell that lexical is launching under can't find the `epmd` command. I use `exec-path-from-shell` to make this work, but this is just a suspicion.

**Comment by scohen** [comment]
Also, if you would like more interactive help, I recommend popping into our discord server. I'm there all the time.

**Comment by scohen** [comment]
Another thing to try would be to run the language server entirely from the command line. 
Assuming you have the following directory structure:
```
parent
  `- lexical
  `- shopex
```

You should be able to go into your `lexical` directory  and do: 
```shell
iex -S mix
```

Then inside iex
```elixir
iex> shopex = project(:shopex)
iex> start_project(shopex)
```
and that should start cleanly. 
You should also be able to trigger completions via:
```elixir
iex> complete(shopex, "Shopex.|")
```

**Comment by nicemaker** [comment]
@scohen Thanks for detailed instructions. I had to switch back to elixir-lsp just because I have a deadline in the next two days.
After that I will be on vacation for a week, but I will come back to this, because I really would love to try lexical. please keep the ticket open for a bit until I am back.

**Comment by scohen** [comment]
@nicemaker I won't close this issue until we figure out what's going on. I'm a emacs user (though I use lsp-mode), and I want to make sure lexical works with eglot.

I tried eglot a while back, and I had to move off because of bugs in how eglot counts code units.

**Comment by nicemaker** [comment]
@scohen After waiting for the bugfix in emacs edge version its working with eglot now! And so far quite smoothly.
You can close this now
