### ISSUE TITLE
Unexpected diagnostic result range type for lsp protocol

### ISSUE THREAD

**Issue by bangalcat** [lexical-lsp/lexical#501]
Recently I started to use [Boundary](https://hexdocs.pm/boundary/Boundary.html) in my project. It checks application boundary rules in compile time. After using the library with lexical, sometimes my neovim lsp shows some weird error messages to me:

![image](https://github.com/lexical-lsp/lexical/assets/16166083/f1fb6801-0c2a-4d52-9767-d0b8381c3378)

After some investigation, I figured out that it is due to wrong data from `textDocument/publishDiagnostics` notification. I injected some logs into both lexical and neovim runtimes and it looked like there were  diagnostic message and the structure of the result being:

```elixir
%LXical.Plugin.V1.Diagnostic.Result{
    details: nil, 
    message: "Storybook.CoreComponents.Button is not included in any boundary", 
    position: {1, 0, 29, 0}, 
    severity: :warning, 
    source: "boundary", 
    uri: "file:///my_app/storybook/core_components/button.story.exs"
}
```

But in neovim log, it said the "range" parameter was in the wrong format. Then I found the [corresponding conversion part](https://github.com/lexical-lsp/lexical/blob/ec2f4cd80db2cbf44cb75a4cd365ce623f861076/apps/server/lib/lexical/convertibles/lexical.plugin.diagnostic.result.ex) in lexical. I think there is a problem. The `position_to_range/2` function in [line 50](https://github.com/lexical-lsp/lexical/blob/ec2f4cd80db2cbf44cb75a4cd365ce623f861076/apps/server/lib/lexical/convertibles/lexical.plugin.diagnostic.result.ex#L50) is building the range with `start` and `end` which are both Range, not Position. The `Lexical.Protocol.Types.Range` specifies its `start` and `end` fields as Position, not Range. As you can see above, `Diagnostic.Result` can have a four-elements tuple as position, and it is converted to `Range{start: Range, end: Range}`. Like this:
`{\"params\":{\"version\":null,\"uri\":\"file:///{file}\",\"diagnostics\":[{\"message\":\"Storybook.Root is not included in any boundary\",\"range\":{\"start\":{\"start\":{\"line\":0,\"character\":0},\"end\":{\"line\":1,\"character\":0}},\"end\":{\"start\":{\"line\":15,\"character\":0},\"end\":{\"line\":16,\"character\":0}}},\"source\":\"boundary\",\"severity\":2}]},\"method\":\"textDocument/publishDiagnostics\",\"jsonrpc\":\"2.0\"}"`

So neovim lsp shows weird error messages.

For workaround, I changed the `position_to_range/2` function to return the proper Range type and it works well so far. Though I'm not sure it is correct behavior. WDYT? Am I missing something behind?

**Comment by scohen** [comment]
Your assessment looks correct. The four element ranges (which we haven't encountered before) should convert to positions, then to a range.

**Comment by scohen** [comment]
the conversion should look like this:
```elixir
  defp position_to_range(%Document{} = document, {start_line, start_column, end_line, end_column}) do
    with {:ok, start_pos} <- Position.new(document, start_line, start_column),
         {:ok, end_pos} <- Position.new(document, end_line, end_column) do
         range = Document.Range.new(start_pos, end_pos)
        Conversions.to_lsp(range)
     end
  end
```

**Comment by bangalcat** [comment]
@scohen Great, I will try to make a PR then.
