### ISSUE TITLE
Lexical textDocument/hover doesn't work in helix

### ISSUE THREAD

**Issue by tcoopman** [lexical-lsp/lexical#506]
I don't get anything - no feedback/nor errors on doing `hover` in helix.

To be fair I'm not sure if this an issue with `lexical` or `helix`, but hover does work in other lsps.
Furthermore, the other features do seem to work with lexical.

**Comment by scohen** [comment]
Does formatting work? Completion?

I don't have any experience with helix, but hover works with vscode, vi, vim, neovim, and emacs.

**Comment by tcoopman** [comment]
Yes all the other things seem to work. Only hover doesn't.

**Comment by scohen** [comment]
interesting. I'm not going to rule out that lexical is emitting some response that's subtly incorrect. If you can give us a debug session for what the responses look like, that would be super helpful.
