### ISSUE TITLE
Error: Config key not found.... on test that uses Mneme

### ISSUE THREAD

**Issue by tcoopman** [lexical-lsp/lexical#507]
![image](https://github.com/lexical-lsp/lexical/assets/45546/916f03ca-84b0-4390-aeb6-84c8b24db9b7)

this is the above error, my `test_helper.exs` does contain `Mneme.start()`

**Comment by scohen** [comment]
@zachallaun this seems right in your wheelhouse.

**Comment by zachallaun** [comment]
Mneme assumes that `test_helper.exs` has already been executed when test modules are compiled. @scohen and I spoke briefly about this and what likely needs to happen is:

1. Lexical should ensure that `test_helper.exs` is evaluated, and
2. ensure that the `System.at_exit` callbacks registered by ExUnit don't run when the VM exits.

**Comment by zachallaun** [comment]
Turns out there's a much easier fix on Mneme's side. I'm going to be cutting a release soon.
