### ISSUE TITLE
Support Elixir 1.16

### ISSUE THREAD

**Issue by scottming** [lexical-lsp/lexical#513]
Elixir 1.16 has two main changes: 

1. the addition of the `span` field, which means diagnostics can be located more precisely; We need to change the diagnostics construction way that is generated by `with_diagnostics.`
2. secondly, in the event of an error in parsing the AST, we need to use certain fields from 'meta' to construct two diagnostics, rather than parsing the message info directly.

**Comment by aerosol** [comment]
Thank you for your work on Lexical. Sorry, does that mean the LSP won't work at all with 1.16 currently, as is?

**Comment by scottming** [comment]
@aerosol yes, you can try the 1.16 support via the linked PR's branch, but you have to mix package that yourself.

**Comment by aerosol** [comment]
Perfect, thank you!

> but you have to mix package that yourself

This is what I do anyway, cheers
