### ISSUE TITLE
Support declaration requests

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#525]
Vscode implements peeking at function definitions (and presumably other things) , but this relies on [declaration/definition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_declaration) which lexical doesn’t support.

**Comment by Terbium-135** [comment]
Just saying:
Peek definition is working for me - but probably you are talking about a different functionality (Not sure if there is even a difference between definition and declaration for the elixir language)

Using this context menu:
![2023-12-24 10_57_26-dashboard_live ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/lexical-lsp/lexical/assets/29901271/92d3097b-d813-4183-a75c-57f9471855e6)

Gives:

![2023-12-24 10_57_04-dashboard_live ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/lexical-lsp/lexical/assets/29901271/d618b8c5-8d19-4919-b5cc-e1a2fb043341)

**Comment by scohen** [comment]
Yes, this was a misunderstanding, we support both requests that enable peek.
