### ISSUE TITLE
Set subfolder as root in VSCode?

### ISSUE THREAD

**Issue by x-ji** [lexical-lsp/lexical#531]
Tried to quick search through the issues and couldn't find a related one. Or maybe I did something wrong here.

In the case VSCode is opened at a parent folder while the Elixir project is in a subfolder, Lexical doesn't seem to work properly. `elixir-ls` has a setting to explicitly set the subfolder as the project root, but I couldn't find a similar setting for Lexical.

(I don't have this issue with Emacs lsp-mode since it asks you to explicitly set the project folder before trying to start the language server.)

**Comment by scohen** [comment]
@Blond11516 is this a client issue or server issue?

Right now, lexical doesn't support multiple workspace folders, so this might be that problem.

**Comment by Blond11516** [comment]
I'll double check tomorrow but I think this might be a server issue. By default the client doesn't specify which folder to start the server in but there may be an option somewhere.

**Comment by Blond11516** [comment]
It can be done on the client. There's a `workspaceFolder` option that lets us start the server anywhere we want. I think it's mostly meant to be used with multi-root workspaces as that's what the official examples do and the interface is a little weird to build by hand, but it works and is pretty simple to implement.

**Comment by Blond11516** [comment]
Hi @x-ji! I've opened a PR on vscode-lexical to add this functionality. If you have some time to check it out and let me know if it works for you I'd greatly appreciate it!

**Comment by Blond11516** [comment]
I just released [version 0.0.12](https://github.com/lexical-lsp/vscode-lexical/blob/main/CHANGELOG.md#0012) of the extension, which adds a new `projectDir` configuration option to enable this.
