### ISSUE TITLE
Undefined function gettext/1 in `app.html.heex`

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#547]
While editing `app.html.heex` (I guess this will happen editing any heex file) an error is shown:

![gettext-error](https://github.com/lexical-lsp/lexical/assets/29901271/85452c61-7657-4d6c-829d-438f65dd5731)

After a recompile the error is gone.
Reporting this more or less for completeness

**Comment by scottming** [comment]
@Terbium-135 Once you save the file, the error diagnostics will disappear, right?

I think this is a known issue, https://github.com/lexical-lsp/lexical/issues/495#issuecomment-1828853060

**Comment by Terbium-135** [comment]
Aye, the diagnostics are disappearing on a save.

**Comment by scohen** [comment]
Duplicate of #495
