### ISSUE TITLE
Reindex command broke LSP initialization in Helix

### ISSUE THREAD

**Issue by mmaa** [lexical-lsp/lexical#551]
The changes in #522 have resulted in Lexical failing to initialize in Helix with the following message:
```
helix_lsp [ERROR] failed to initialize language server: failed to parse: invalid type: boolean `true`, expected struct CodeLensOptions
```

I'm running the latest version (master) of Helix.

I'm not sure what other info would be useful to provide. Please let me know what else I can do to help track this down.

**Comment by scohen** [comment]
This is very helpful, thank you.

**Comment by scohen** [comment]
@mmaa, if I've pushed #553, if you can verify that branch works, it'd be helpful. 
I have high confidence it will though.

**Comment by mmaa** [comment]
That did it. Thanks!

**Comment by scohen** [comment]
Sweet, sorry about the bug.
