### ISSUE TITLE
`mix deps.compile` running on each time a project gets opened

### ISSUE THREAD

**Issue by Qizot** [lexical-lsp/lexical#564]
# Problem
I'm using neovim 0.9 and each time I open a project `mix deps.compile` gets to run. The problem is that until it finishes I can't do anything since the LSP is not yet fully running.

When nothing changes I would expect it not to run the `deps.compile`, it is quite annoying when jumping between projects by closing and opening them.

Is it intentional or am I doing something wrong/wrong setup?

**Comment by zachallaun** [comment]
You're not doing anything wrong; this is a limitation at the moment, but one that is very soon to be resolved when #560 is completed. See: https://github.com/lexical-lsp/lexical/issues/560#issuecomment-1897501607

**Comment by scohen** [comment]
We'll need some changes after #560 to address this issue, but it's intended for the 0.5 release. This should _drastically_ speed up Lexical's boot process.

**Comment by scohen** [comment]
..and to be clear, we will still run `mix deps.compile` when the project starts, but if they're up to date, the compilation should be quick. Prior, we were running `mix deps.clean` and `mix clean` on project start.

**Comment by scohen** [comment]
Closed this, feel free to reopen if this is still an issue
