### ISSUE TITLE
Duplicate error messages on restart

### ISSUE THREAD

**Issue by ilourt** [lexical-lsp/lexical#578]
Each time I restart the lsp (in vim in my case), diagnostics messages stays and after restart they are duplicated.

Before restart:
![SCR-20240126-kzyj](https://github.com/lexical-lsp/lexical/assets/3799113/2b145920-77d4-406b-8206-f4bd13b9398b)

Aftrer restart:
![SCR-20240126-laiy](https://github.com/lexical-lsp/lexical/assets/3799113/1094e76b-c81b-4190-9ba1-9e8b80518373)

I don't have this problem with other LSP.

By the way thanks for the greatjob you have done with lexical 👍

**Comment by scottming** [comment]
Firstly, I would like to know how you restarted `vim`'s LSP and why. Did you use the `LspRestart` command?

Additionally, I seem to be unable to reproduce your issue.

![CleanShot 2024-01-26 at 19 23 44@2x](https://github.com/lexical-lsp/lexical/assets/12830256/176f7964-3602-4bc8-b14a-107c2a0f0a96)

**Comment by ilourt** [comment]
Yes I use `:LspRestart` to restart the lsp. I have to do this sometime because even if I correct my code I still have the error displayed in the editor. After the Lsp has restarted the error is gone. But other errors (which are still present in my code) are duplicated.

For more information about my setup:
- neovim v0.9.4
- lsp-zero https://github.com/VonHeikemen/lsp-zero.nvim
- trouble https://github.com/folke/trouble.nvim

**Comment by ilourt** [comment]
I just try with a new project, and I can't reproduce the problem.

Do you think it is possible that this problem arise when the project reach a given size?

**Comment by scottming** [comment]
I don't think this is related to the size. You need to set the log level to debug(`lua vim.lsp.set_log_level("debug")`) and check the `LspLog` to see if Lexical is actually generating duplicate diagnostics for you or if it's because nvim started two clients for you.

**Comment by ilourt** [comment]
For information, after more search I found that only errors for the current buffer was cleaned on LspRestart which cause to having duplicate errors.

My solution:
```lua
vim.keymap.set("n", "<leader>rr", "<cmd>LspRestart<CR><cmd>lua vim.diagnostic.reset()<CR>")
```

It restart the lsp and reset all errors in the diagnostic

Thanks @scottming  to help me

**Comment by scottming** [comment]
> Sometimes, I dont know why, I have a problem of error message still present even if I have corrected my code


@ilourt  In this case, you can check the `.lexical/lexical.log` file to see if there are any crashes. If there are crashes, feel free to submit a reproducible issue so that we can fix it thoroughly.

Another situation I've noticed is that when multiple editors are editing, there can be document synchronization issues. In such cases, you can simply use `:e` command  to reload the document file, which is much faster than restarting the LSP.

**Comment by ilourt** [comment]
@scottming I will let you know if I have more clue about why this is happening
