### ISSUE TITLE
Only index definitions on in dependencies by default

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#590]
In order to save memory, and avoid cluttering search results, we should not index references in dependencies.

**Comment by aptinio** [comment]
Is it enough to filter out files within the `deps` directory from here?

https://github.com/lexical-lsp/lexical/blob/2c49cd5d5609606c57a3f8eb11776e295b29f3d8/apps/remote_control/lib/lexical/remote_control/search/indexer.ex#L155-L161

**Comment by scottming** [comment]
@aptinio no, I think we still need to index the definitions of deep

**Comment by aptinio** [comment]
So, only index deps' definitions, but not their references. Got it. Thanks @scottming.

**Comment by scohen** [comment]
@aptinio I'm sorry, I started on this before I saw your comments, looks like you were looking in the right place.

**Comment by aptinio** [comment]
No problem @scohen. :relaxed:
