### ISSUE TITLE
Lexical fails to start with Elixir 1.16.0-rc (installed through asdf) in VScodium 

### ISSUE THREAD

**Issue by guillermo-st** [lexical-lsp/lexical#623]
Here is the error log:

```
Starting Lexical in directory /home/guillermo/Code/exercism/elixir/boutique-suggestions
Starting lexical release in "/home/guillermo/.config/VSCodium/User/globalStorage/lexical-lsp.lexical/lexical_install/lexical/bin/start_lexical.sh"
Detected Elixir through asdf: /home/guillermo/.asdf/installs/elixir/1.16.0-rc.1-otp-26/bin/elixir
FATAL: Lexical is not compatible with Elixir 1.16.0-rc

Lexical is compatible with the following versions of Elixir:

  >= 1.13.0
  >= 1.14.0
  >= 1.15.3
  >= 1.16.0

[Error - 7:50:58 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 7:50:58 PM] Connection to server got closed. Server will restart.
true
[Error - 7:50:58 PM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
 ```
 
 Then it proceeds to try again a few times until it gives up. What am I doing wrong? Lexical is available in vscodium's repository so I figured it would be as compatible as with vscode. Is is because of the `-rc` suffix on my Elixir version? It was the latest one at the moment of installation in asdf.

**Comment by scottming** [comment]
Why don't you just use 1.16.0 or 1.16.1?

**Comment by guillermo-st** [comment]
> Why don't you just use 1.16.0 or 1.16.1?

I'm new to elixir and just intalled whatever the last available version was at the moment int asdf. Should I switch to the plain 1.16.1 version, or 1.16.1-otp-26? I know I have the OTP26 erlang version installed

**Comment by scottming** [comment]
1.16.1-otp26 is supported

**Comment by scottming** [comment]
Thanks for your reporting, I'll update the doc.

**Comment by scottming** [comment]
I'm not familiar with Emacs configuration, but you can try it out. If there are any issues, you can continue to report them here, and other maintainers who use Emacs will respond.

@guillermo-st
