### ISSUE TITLE
Adding a CHANGELOG

### ISSUE THREAD

**Issue by pierrelegall** [lexical-lsp/lexical#626]
I'd like to see a `CHANGELOG.md` in this repository to have a better understanding of features/improvements/fixes & more at each new versions :heart:

Maybe using something like [convertional commits](https://www.conventionalcommits.org/en/v1.0.0/) can help :smiley:

**Comment by scohen** [comment]
Is the changelog[ at the top of the releases not sufficient](https://github.com/lexical-lsp/lexical/releases)?

**Comment by scohen** [comment]
Ah, I think you want to see changes _between_ releases.  Is that correct?

**Comment by pierrelegall** [comment]
I didn't notice the changes note in the release section, sorry for the miss.

+1 for the "Full Changelog" link :)

**Comment by scohen** [comment]
Let's keep this open, then
