### ISSUE TITLE
No completions offered on typing `do`for functions and for loops

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#660]
For me function heads and for loops are lacking then completion * do/end* block.

![2024-03-25 20_14_01-● layout_builder ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/lexical-lsp/lexical/assets/29901271/ea990a1c-6439-4306-b4b5-1c2520397437)

![2024-03-25 20_13_48-● layout_builder ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/lexical-lsp/lexical/assets/29901271/8f25258e-42fb-4ad1-8fe8-5b5dbbd8b24a)

![2024-03-25 20_13_12-● layout_builder ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/lexical-lsp/lexical/assets/29901271/c5aba823-19e4-4d7c-8567-a89892136d59)

**Comment by scohen** [comment]
I definitely get completions in emacs for `do/end` for `def/defp/defmodule`. I think this is because vscode isn't re-requesting completions after the ones for `def`. This is a longstanding bug in vscode, and is detailed here:
#400

**Comment by Terbium-135** [comment]
I see.
Thank you for pointing me at this.
Closing this issue
