### ISSUE TITLE
Architecture and Glossary pages links not working

### ISSUE THREAD

**Issue by lucazulian** [lexical-lsp/lexical#668]
On the [Architecture](https://github.com/lexical-lsp/lexical/blob/main/pages/architecture.md) and [Glossary](https://github.com/lexical-lsp/lexical/blob/main/pages/glossary.md), some links inside are not working; they point to something that does not seem to exist anymore. For example: [LSP Request](`Lexical.Protocol.Requests`). It seems to point to the module `Lexical.Protocol.Requests`, but I'm not sure this is the correct way to link that one.

**Comment by Moosieus** [comment]
The broken links appear relegated to the architecture page, the above PR should fix them.
