### ISSUE TITLE
module LXical.Server.Boot is not available

### ISSUE THREAD

**Issue by karangejo** [lexical-lsp/lexical#699]
I pulled the project down and ran
mix deps.get
mix package

Afterwards when I run 
./bin/start_lexical.sh
 
I get this output
Detected Elixir through asdf: /Users/my_user/.asdf/installs/elixir/1.16.0-otp-26/bin/elixir
** (UndefinedFunctionError) function LXical.Server.Boot.start/0 is undefined (module LXical.Server.Boot is not available)
    LXical.Server.Boot.start()
    boot.exs:23: (file)

**Comment by scohen** [comment]
You are running `./bin/start_lexical` you should be running `_build/dev/package/bin/start_lexical.sh`
