### ISSUE TITLE
Feature request: Include def or defp in document symbols

### ISSUE THREAD

**Issue by crbelaus** [lexical-lsp/lexical#701]
The document symbols provider is not showing any information that allows you to identify whether a function is public or private.

The following is a screenshot from VSCode with Lexical showing all the symbols in a particular module. Only `changeset/2` and `url/2` are public functions, while the rest are private.

![image](https://github.com/lexical-lsp/lexical/assets/2965623/d57d5d19-84fa-4115-af17-958dc1cf3b69)

For comparison, this is the same module with ElixirLS in this case. Notice the `def` and `defp` before the function names.

![image](https://github.com/lexical-lsp/lexical/assets/2965623/d08a2266-d435-40e8-b746-51d8cfecaa04)

I'm just opening this issue as a potential feature request open for discussion. I personally find this functionality very useful as it allows me to easily see the public interface of a particular module without having to perform a `def ` search.

**Comment by scohen** [comment]
@scottming suggested using different icons for public and private functions, but they're actually meant to distinguish between methods and functions and don't have any intrinsic meaning.

**Comment by scohen** [comment]
@crbelaus How about if we put a little lock icon in front of private functions? Like this:        
![Screenshot 2024-04-17 at 2 33 56 PM](https://github.com/lexical-lsp/lexical/assets/55809/9a5aeb60-b07a-44c9-89fd-02f028772c18)

**Comment by scohen** [comment]
I tried making public functions function kinds and private functions method kinds, but in emacs at least, they use the same icon.

**Comment by Terbium-135** [comment]
Personally I'd prefer written text `def/defp` instead of another symbol in front. Second symbol looks overloaded to me. But this is UI and everyone to his taste.
Anything will do a long as there is something at all

**Comment by scottming** [comment]
> @crbelaus How about if we put a little lock icon in front of private functions? Like this:

I favor the small lock icon: : `\uea75`; it is very effective for quick visual recognition, and it will be easy to remove or modify when the official LSP adds more symbol tags in the future. Although 'def' and 'defp' are somewhat helpful in searches, they are a distraction when viewing symbols.

**Comment by crbelaus** [comment]
The proposed small lock icon sounds good 👍 

I mentioned `def` and `defp` on the issue because that is what ElixirLS does but any other solution that helps identifying public and private functions is great.

**Comment by zachallaun** [comment]
I'd prefer `def/defp` as it naturally extends to including `defmacro` and `defmacrop` as well. It would also be helpful to distinguish between functions and macros, and the lock does not give any of that info. (Workspace symbols doesn't currently include macro definitions but I expect that it will in short order.)

**Comment by scohen** [comment]
macros will have a different icon

**Comment by scohen** [comment]
I worry about defmacro/defmacrop + the function name + the arguments will be a _lot_ of noise in the sidebar.

**Comment by zachallaun** [comment]
> I worry about defmacro/defmacrop + the function name + the arguments will be a lot of noise in the sidebar.

@scohen Devil's advocate: I like that types, for instance, include `@type` before them. If I'm looking at symbols and only care about types, I can quickly type `@type` to narrow down to only those. The same could be useful for defs/defmacros.

**Comment by scohen** [comment]
That's fair and this stuff is super easy to change.
