### ISSUE TITLE
Corporate laptop Lexical fails to connect

### ISSUE THREAD

**Issue by GenericJam** [lexical-lsp/lexical#723]
I'm working on a pretty locked down corporate M2 Macbook that is managed extensively with a lot of programs that I can't stop running. The network is managed. I have to use a VPN if not in the office, etc.

I'm using the latest main branch source.

I suspect this is not related but `iex` is often delayed by many seconds when starting and sometimes it's delayed by so long it gets killed by the OS as it is deemed unresponsive.

In the past it was working and if it wasn't working I could turn the WiFi off and restart VSCode, lexical would start and I could turn the WiFi back on and lexical would keep working.

I suspect something in my environment changed with some sort of invisible upgrade. I wish I could provide more detail but this is about as much as I know.

Edit: logs removed

**Comment by scohen** [comment]
This is the problem
```
20:44:23.737 [error] Process :"arrow_ex::node_process" (#PID<0.1557.0>) terminating
** (exit) :start_timeout
    (stdlib 5.2.2) gen_server.erl:1226: :gen_server.handle_common_reply/8
    (stdlib 5.2.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Initial Call: LXical.RemoteControl.ProjectNode.init/1
```

this is happening deep within otp, we're not doing anything crazy here. You are not being well served by your it department when you can't do work due to draconian and incorrect "security" policies if iex can't reliably run, how can lexical?

**Comment by scohen** [comment]
Closing this as there's not much I can do to improve this situation.
