### ISSUE TITLE
Document symbols don't include defdelegate macros

### ISSUE THREAD

**Issue by crbelaus** [lexical-lsp/lexical#724]
As shown in the following screenshot, the document symbols don't include the `defdelegate` macro. Both the `save_changeset` and `update` functions are included, but `create` is not.

![image](https://github.com/lexical-lsp/lexical/assets/2965623/37e1408e-03c9-4663-923e-073b0aa7f25d)

I'm not sure if this is intentional or not, as I've tried to create another macro myself and it is not included either.

**Comment by scohen** [comment]
it's merely overlooked, not a bug per se, I didn't include defdelgate in the list when building document symbols.

**Comment by scohen** [comment]
@crbelaus give this a shot and tell me what you think.
