### ISSUE TITLE
Struct autocomplete: Show the type

### ISSUE THREAD

**Issue by kirillrogovoy** [lexical-lsp/lexical#749]
Hey,

Lexical is fantastic! ❤️

Sorry if this issue has already been mentioned. Could not find anything in the issues.

When ElixirLS completes access to a struct field, it shows some type information (given that the struct has a spec):

<img width="1452" alt="Screenshot 2024-05-22 at 16 52 10" src="https://github.com/lexical-lsp/lexical/assets/4512269/8d900cfe-7bb5-42ce-b7a4-fe39a81d22c5">

However, Lexical doesn't (the examples are from Neovim and VS Code respectively):

<img width="739" alt="Screenshot 2024-05-22 at 16 49 55" src="https://github.com/lexical-lsp/lexical/assets/4512269/f7bc56b1-2538-4c62-a049-e2a162de926b">

<img width="1027" alt="Screenshot 2024-05-22 at 16 48 31" src="https://github.com/lexical-lsp/lexical/assets/4512269/4f99d567-2c0e-4a5d-80c6-7a202929ba13">

Is there an easy way to fix that? 🤔 I have very little experience in LSP but happy to jump in with some guidance.

**Comment by scohen** [comment]
I'll add that the types you've shown seem to do little other than add noise though. That's a lot of text to tell you that it's a struct field of type `Payload{}`. From a product perspective, we'll have to figure this out.

**Comment by kirillrogovoy** [comment]
Yeah, the part you are referring to is noise.

I was referring to the type spec info specifically.

I've actually just done it locally!! (this is Lexical)
<img width="930" alt="image" src="https://github.com/lexical-lsp/lexical/assets/4512269/cf2efe2f-a8fa-4879-b78c-adea600f8425">

Shipping a PR soon to show what I did.

**Comment by kirillrogovoy** [comment]
The info is already there in the ElixirSense suggestion (type_spec field), so it's super simple.

**Comment by scohen** [comment]
are those just the details? If so, this would be extremely simple

**Comment by scohen** [comment]
It doesn't look like I've mapped the `type_spec` field of the elixirsense suggestion to the `Candidate.StructField` struct, so you'll need to do that as well.  That's in [here](https://github.com/lexical-lsp/lexical/blob/a0d543a189820d8ab9f735ed7f101cf324efc6cd/apps/remote_control/lib/lexical/remote_control/completion/candidate.ex#L160)
