### ISSUE TITLE
Failed to start Lexical, couldn't create connection to server

### ISSUE THREAD

**Issue by chrisnaadhi** [lexical-lsp/lexical#762]
![image](https://github.com/lexical-lsp/lexical/assets/29543851/f1867b96-eabd-4091-b3aa-8eed8e6e833d)

hello! 
it's my first time using lexical and i got this error message.
i've tried to install via marketplace and follow the instructions in the github readme of installation but i got no clue why the client can't create connection
the debug output :
![image](https://github.com/lexical-lsp/lexical/assets/29543851/e6d6db55-73e0-410d-823e-b1b394780ff3)

system i'm using : 
Windows 10 64-bit
Erlang version 26.2.2
Elixir version 1.16.1

**Comment by chrisnaadhi** [comment]
![image](https://github.com/lexical-lsp/lexical/assets/29543851/08037ef2-89de-4ef7-b140-d772049781ad)
trying to build from the source also failed

**Comment by Terbium-135** [comment]
Looks like you are trying to start lexical using windows
That line:
`"c:\Users\chris\AppData\.......\start_lexial.sh"`
tries to start a script meant for linux
There should be a `.bat` file which fits windows

**Comment by scohen** [comment]
Windows is only supported with wsl at the moment. I would love to support windows, but don't have a windows machine to test on.
