### ISSUE TITLE
LSP is not suggesting some Kernel operators

### ISSUE THREAD

**Issue by krainboltgreene** [lexical-lsp/lexical#832]
![Screenshot 2024-10-11 at 2 28 02 PM](https://github.com/user-attachments/assets/f6ba699e-f9f0-4840-a602-32d5b2ae8c1f)
![Screenshot 2024-10-11 at 2 28 09 PM](https://github.com/user-attachments/assets/828928b2-ff71-48f1-aa82-13afb7cae476)

It looks like it only sees two operators with `=`?

**Comment by Moosieus** [comment]
Certain macros are currently ignored [here](https://github.com/lexical-lsp/lexical/blob/main/apps/server/lib/lexical/server/code_intelligence/completion/translations/callable.ex#L9-L14):

```elixir
@syntax_macros ~w(= == == === =~ .. ..// ! != !== &&)

def completion(%_callable_module{name: name}, _env)
    when name in @syntax_macros do
  :skip
end
```

This clause could be removed, or an exception could be made for `Kernel.|` like so:
```elixir
def completion(%_callable_module{name: name} = callable, %Env{} = env)
    when name in @syntax_macros do
  if String.ends_with?(env.prefix, "Kernel.") do
    do_completion(callable, env)
  else
    :skip
  end
end
```

**Comment by krainboltgreene** [comment]
That makes a ton of sense.

**Comment by scohen** [comment]
@Moosieus PR for this?
