### ISSUE TITLE
Supporting Custom Def jump to location support 

### ISSUE THREAD

**Issue by mariari** [lexical-lsp/lexical#834]
In a codebase I work on we have a macro called defbug

```elixir
  @doc """
  I am the function definition macro for debugging.

  I mainly should be used on functions which satisfy:

  1) Needing to be private i.e. not expose API to other Engines.
  2) Important for core functionality and hence requiring documentation.

  Given the two are satisfied, use me to define a function which becomes
  public once in debug mode and otherwise remains private.

  I am to be used alongside the `docp/1` macro to allow for good
  documentation practices.
  """

  defmacro defbug(name, expr \\ nil) do
    if Mix.env() == :debug do
      quote do
        def(unquote(name), unquote(expr))
      end
    else
      quote do
        defp(unquote(name), unquote(expr))
      end
    end
  end
```

which is very nice for when debugging turning private functions into public functions. 

Finding references with lexical works well for this. however, when used with jump to definition, it seems not to work at all:

![](https://pomf2.lain.la/f/4vsiwu7y.png)

I just get not found. However if I switch it back to a `defp` or `def` go to definition works as expected.

**Comment by m1dnight** [comment]
I made a branch that has a test in it that should pass if this were to work, I believe: 
https://github.com/m1dnight/lexical/tree/def_with_macro

**Comment by Moosieus** [comment]
go-to-definition for functions produced by macros like this would require macro expansion during indexing.

At this point, this issue is *won't fix* for Lexical, and a consideration for Expert.
