### ISSUE TITLE
unit in `bitstring` caught up the double colon

### ISSUE THREAD

**Issue by padulkemid** [lexical-lsp/lexical#837]
I'm not sure but this not happened in other completion stuff (AFAIK) only in bitstring
![lexical_bitstring](https://github.com/user-attachments/assets/b3ac29a0-a65c-4280-9b5f-46a859de5964)

**Comment by Moosieus** [comment]
I gave this a quick test in VSCode, but the completion seems to be working as intended. Can you share which editor you're using and what version of Lexical you're running?

**Comment by padulkemid** [comment]
@Moosieus using `neovim` 0.10.2 and using `lexical` 0.7.1

**Comment by padulkemid** [comment]
i think this is more of IDE issue, I had go through the lexical code and change stuff but it calls the buffer write from neovim @Moosieus we can close this I think (I forgot to check up this issue lol since I already go through all the stuff) prolly in the LSP bridge to buffer
