### ISSUE TITLE
Elixir 1.17 and OTP 27

### ISSUE THREAD

**Issue by nicemaker** [lexical-lsp/lexical#838]
According to docs elixir 1.17 and otp 27 should be supported now.
Thanks for the work on that, very much appreciated.

I am facing a problem though. Maybe I am just missing something stupid.

I upgrade to the latest elixir version  including OTP 27.
I completely removed my lexical repository clone just to be sure I have the most up to date version 1.7.1 and all bins are cleared.
After `mix package` I restarted my emacs with eglot but got an error when opening an elixir file 
`error in process sentinel: [eglot] -1: Server died`

I tried to start the lexical server manually by
 ```
 ~/lexical/_build/dev/package/lexical/bin/start_lexical.sh 
 ```
 
 and got 
 
 ```
 Detected Elixir through asdf: /home/bjorn/.asdf/installs/elixir/1.17.0-otp-27/bin/elixir
FATAL: Lexical is not compatible with Elixir 1.17.0

Lexical is compatible with the following versions of Elixir:

  >= 1.13.0
  >= 1.14.0
  >= 1.15.3


FATAL: Lexical is not compatible with Erlang/OTP 27.1.2

Lexical is compatible with the following versions of Erlang/OTP:

  >= 24.3.4
  >= 25.0.0
  >= 26.0.2
```

I first tried elixir 1.17.3, then went down to 1.17.0 and the also downed OTP to 26.
OTP 26 is accepted but I still get the error for elixir.

**Comment by nicemaker** [comment]
I also just read that Lexical, Next LS and Elixir LS is in the process of merging. Thats great I believe. So maybe you don't have time to focus on that topic mentioned above.

**Comment by scohen** [comment]
Do you have the latest from `main`? Lexical built from source has supported 1.17 for a while. I've got some performance stuff queued up after which I'll do a release.

**Comment by scohen** [comment]
Closing because this feels like a local issue. Feel free to reopen or drop by the lexical discord.

**Comment by nicemaker** [comment]
Sorry for late late reply. 
I completely reinstall my OS over the holidays and now its working. 
No idea why it failed back then. Pretty sure that I was on main branch and had the right erlang/elixir versions selected, but it must have been indeed some local issue then.

Thanks for your effort
