### ISSUE TITLE
Elixir 1.18: Formatting to curly braces within lexical creates wrong code in sigil ~H 

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/lexical#843]
Running `mix format xxx.ex` from the command line gives the correct result.

Formatting with lexical (and also on save) produces incorrect code.

The line
            `<%= gettext("Transaction") %> ➜ <%= gettext("Show details") %>`
becomes:
            `{gettext("Transaction")} ➜ <%{ttext("Show details") %}`

**I have the gut feeling that the unicode character is breaking lexical's formatting function**

xxx.ex:
```elixir
defmodule BackendWeb.PointOfSale.EventLogLive do
  use BackendWeb, :live_view
  use Gettext, backend: BackendWeb.Gettext

  @impl true
  def render(assigns) do
    ~H"""
    <%= if connected?(@socket) do %>
      <section id="eventlog-dialogs">
        <.eventmodal id="modal-log-info" on_confirm={} show={false} class="max-w-[64rem]">
          <.newheader class="text-left text-zinc-300 text-xl bg-teal-900 p-2 rounded-lg">
            <%= gettext("Transaction") %> ➜ <%= gettext("Show details") %>
          </.newheader>
        </.eventmodal>
      </section>
    <% end %>

    """
  end
end

```

**Comment by scohen** [comment]
Lexical does not support 1.18 yet. It is not capable of running under 1.18, and your version is running under a different version of elixir, which is why you're getting a different result than when you format with `mix format`.
