### ISSUE TITLE
Unable to start despite detection of compatible version

### ISSUE THREAD

**Issue by achou11** [lexical-lsp/lexical#845]
I'm trying to use Lexical via the VSCode extension (0.0.18). Please let me know if I should move this issue to that repo instead!

I have Elixir 1.17.3-opt-27 installed using mise with a local configuration (I have 1.18-opt-27 installed at the global level). When I start my editor, the lsp fails to start and has the following output:

```sh
[info] Lexical client is not running. Starting.
[info] Detected Elixir through mise: /Users/andrewchou/.local/share/mise/installs/elixir/1.17.3-otp-27/bin/elixir

[info] FATAL: Lexical is not compatible with Elixir 1.18.0
```

Seems like the detection is working properly at least, but I guess it's not using the correct version to actually start the server.

**Comment by x-ji** [comment]
Same. I even specified 1.17.3-otp-27 as the global version as well. In the end I had to uninstall 1.18.0-otp-27 to make it work.

**Comment by scohen** [comment]
Lexical doesn't yet support 1.18. I'll open an issue for that.

**Comment by achou11** [comment]
> Lexical doesn't yet support 1.18. I'll open an issue for that.

Not sure why this issue is closed, as this is separate from the issue I've reported. I'm referring to Lexical attempting to use the incorrect Elixir path despite correctly detecting a compatible one. Unless I've hit very specific circumstances, this will be a problem for anyone attempting to use Lexical on a project that uses a compatible Elixir version that isn't necessarily the latest one.
