### ISSUE TITLE
Remove Build locks?

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#92]
I can't for the life of me remember why I added the build locks. 
Builds presently go through the build genserver, which means that only one thing will progress at a time, so we shouldn't need locks. 
I was noticing some stalling in the app yesterday, and disabled locks which cured the stalling and didn't seem to have any side effects.

**Comment by scottming** [comment]
Because at that time, the specific reason why the format did not work on another node was not found, so you added a lock.

**Comment by scottming** [comment]
I am happy to remove all locks. Currently, locks have caused many problems, such as the inability to use as-you-type when a project has yet to finish compiling or before trace.

**Comment by scottming** [comment]
I can submit a pr for this:

https://github.com/scottming/lexical/compare/fix-terminator-highlighting-issue...scottming:lexical:remove-with-lock?expand=1

**Comment by scohen** [comment]
> yeah, Currently, locks have caused some problems, such as the inability to use as-you-type when a project has yet to finish compiling or before trace

So to be clear, you will still have this issue, because all compilation goes through a single genserver which processes messages sequentially.

> yeah, Currently, locks have caused some problems, such as the inability to use as-you-type when a project has yet to finish compiling or before trace

Yep, that's why they're there. I think this can also be solved by moving the `in_mix_project` function from `remote_control` to inside the build genserver.
