### ISSUE TITLE
Move off of `:slave` in remote control.

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#93]
The erlang `:slave` module has the following drawbacks:

  1. It shares IO and file servers with the node that started it. This means the server's `cwd` is constantly changing
  2. It's started by the server node, which means the version of erlang is the same as the one on the server node. This means that projects that declare a different erlang version won't be running in the correct version
  3. It's deprecated
  4. It has a very regrettable name.

I'd suggest moving over to `:peer`, which fixes the first, third and fourth problems, but it still will have the second and it's new in erlang 25. I'd like to have at least two erlang versions of compatibility.

We should investigate starting up our own node and bootstrapping it. We already do this to some extent with `remote_control` so I wonder how hard it would be to launch a blank node and then add the libraries to it.

**Comment by scottming** [comment]
To be honest, I have looked at some docs and it seems that we can start a node using `escript` or `mix run --no-halt`, but I still don't know how to do it, especially bootstrapping.
