### ISSUE TITLE
Feature: Code action - Organize aliases

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#94]
This is actually a tough one. I tried implementing this in elixir-ls but gave up because it didn't have good enough source code editing tooling. 

Initially, we should enforce the following:

Flatten nested aliases `Foo.Bar{Baz, Quux}` 
Sort aliases alphabetically

Be aware though; Aliases can depend on one another
```elixir
alias Lexical.RemoteControl
alias RemoteControl.Build 
alias Build.Server
```
This should result in:
```elixir
alias Lexical.RemoteControl
alias Lexical.RemoteControl.Build
alias Lexical.RemoteControl.Build.Server
```
Similarly, nested aliases can have internal dependencies and external dependencies

Also, aliases can appear anywhere in a source file. Aliases inside function definitions cannot be pulled out of those definitions. Aliases that are present in an outer context are visible in an inner context. So
```elixir
defmodule Outer do 
  alias Lexical.RemoteControl 

  defmodule Inner do 
    def my_fun do 
      RemoteControl.foobar()
   end
end
```
is valid.

**Comment by scottming** [comment]
I think this enhancement can be solved by plugins when we have the `code action` plugin type.
