### ISSUE TITLE
Add ability to send messages to the server

### ISSUE THREAD

**Issue by scohen** [lexical-lsp/lexical#96]
Presently we don't have the ability to notify the user of... stuff. 

To fix this, we need to implement
[`window/showMessage`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage)
[`window/showMessageRequest`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest)
[`window/logMessage`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_logMessage)

**Comment by skbolton** [comment]
Is there more specifics on what needs to be done here? Looking through the code the protocol definitions are already [defined](https://github.com/skbolton/lexical/blob/085a27a1bb136df8543e0fd31cc5c8c4549cec29/apps/protocol/lib/lexical/protocol/notifications.ex#L64-L88). Hacking on this I added an additional `Transport.write` with the log message and it showed up in neovim's lsp logs.

Is the work of this to run around all the places that logging is happening and also sending those through as lsp logs?
